name: f_learner
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flame: ">=1.30.1 <1.33.0" # 游戏引擎
  volume_controller: ^3.4.0 # 音量控制
  open_file: ^3.5.10 # 原生打开文件
  open_file_ohos: # 鸿蒙原生打开文件
    # 两个版本都依赖，但使用的时候导入open_file_ohos就都能用
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_open_file.git"
      path: "ohos"
  file_selector: # 文件选择器.鸿蒙适配
  lottie: ^3.3.1 # lottie动画
  flutter_svg: ^2.2.0
  # switch(defaultTargetPlatform)缺少TargetPlatform.ohos
  # flutter_quill: ^11.4.2
  # flutter_quill_extensions: ^11.0.0
  re_editor: ^0.8.0
  flutter_staggered_grid_view: ^0.7.0
  # switch(defaultTargetPlatform)缺少TargetPlatform.ohos
  fleather: ^1.26.0
  image_picker: # 图片选择.鸿蒙适配
  url_launcher: # 打开链接.鸿蒙适配
  vector_math: ^2.1.4
  gpt_markdown: ^1.1.2
  appflowy_editor: ^6.1.0
  provider: ^6.1.5+1
  universal_html: ^2.2.4
  markdown: ^7.3.0
  google_fonts: ^6.3.2
  file_picker: ^10.3.3
  # file_picker_ohos: # 文件选择.鸿蒙适配
  #   git:
  #     url: https://gitcode.com/openharmony-sig/fluttertpc_file_picker.git
  #     path: ohos
  path_provider: # 应用可用路径.鸿蒙适配
  share_plus: # 分享.鸿蒙适配
  vyuh_node_flow: ^0.2.5
  shared_preferences: # 存储.鸿蒙适配
  archive: ^4.0.7 # 压缩
  path: ^1.9.1 # 文件路径
  printing: ^5.14.2 # 打印
  pdf: ^3.11.3 # pdf

dependency_overrides:
  printing: # 打印.鸿蒙适配
    git:
      url: https://gitcode.com/openharmony-sig/fluttertpc_printing.git
      path: printing
      ref: br_printing-v5.14.2_ohos
  shared_preferences: # 存储.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.5.3_ohos"
  file_selector: # 文件选择器.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/file_selector/file_selector"
  image_picker: # 图片选择.鸿蒙适配
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/image_picker/image_picker
  url_launcher: # 打开链接.鸿蒙适配
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/url_launcher/url_launcher
      ref: br_url_launcher_v6.3.1_ohos
  path_provider: # 应用可用路径.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  share_plus: # 分享.鸿蒙适配
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/share_plus/share_plus
      ref: br_share_plus-v10.1.1_ohos

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottiefiles/
    - assets/img/
    - images/
    - assets/images/
    - assets/font/
